# -*- coding: utf-8 -*-
"""dataanalysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DQ7xDNtVp_jPkrbr_wnDLBaTtCT-mnQK
"""

#import drive
from pydrive.drive import GoogleDrive #connect to drive
from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
data = '/content/drive/MyDrive/Hawsabah/Snapchat.xlsx'
df=pd.read_excel(data)
#print(df.columns)
#df.head

def ContainZeroAndPercent(col):
  return all(value == 0 or value == '0.00%' for value in col);

df = df.loc[: , ~df.apply(ContainZeroAndPercent)]
print(df.columns);

output_path = '/content/drive/MyDrive/Hawsabah/Snapchat_filtered.xlsx'

# Save the filtered DataFrame to an Excel file
df.to_excel(output_path, index=False)


# Display the filtered DataFrame
df;

df = df.loc[: , ~df.apply(ContainZeroAndPercent)]
print(df.columns);

output_path = '/content/drive/MyDrive/Hawsabah/Snapchat_filtered.xlsx'

# Save the filtered DataFrame to an Excel file
df.to_excel(output_path, index=False)


# Display the filtered DataFrame
df;

print(df.columns);

output_path = '/content/drive/MyDrive/Hawsabah/Snapchat_filtered.xlsx'

# Save the filtered DataFrame to an Excel file
df.to_excel(output_path, index=False)


# Display the filtered DataFrame
df;

df;
output_path = '/content/drive/MyDrive/Hawsabah/Snapchat_filtered.xlsx'

# Save the filtered DataFrame to an Excel file
df.to_excel(output_path, index=False)

# Print the columns of the filtered DataFrame
print(df.columns)

# Display the filtered DataFrame
df;

df

output_path = '/content/drive/MyDrive/Hawsabah/Snapchat_filtered.xlsx'

# Save the filtered DataFrame to an Excel file
df.to_excel(output_path, index=False)

# Print the columns of the filtered DataFrame
print(df.columns)

# Display the filtered DataFrame
df;